### ISSUE TITLE
[BUG] All opened documents blank

### ISSUE THREAD

**Issue by tonhou** [UberWriter/uberwriter#171]
When a previous markdown document is opened it displays no text. Document statistics show zero words and zero characters, but the name of the document shows at top of window.

**Steps to reproduce the behavior:**
1. Open any previous markdown document
2. No text displayed
3. If another editor allows "copy as markdown", this can be pasted in to Uberwriter and displays correctly. From here this document can be manipulated and exported without issue.

**Environment:**
- Linux distribution: Mageia 7
- Desktop Enviroment: Plasma 
- DE version: 5.15.4
- GTK version: GTK+3.0/3.24.8

This behaviour present with flatpak version 2.1.5
Also after installing dependencies and running as described here:

*You can run UberWriter with ./bin/uberwriter without installing it in the system, but you'll need to install and compile the schemas before: sudo cp data/de.wolfvollprecht.UberWriter.gschema.xml /usr/share/glib-2.0/schemas/de.wolfvollprecht.UberWriter.gschema.xml sudo glib-compile-schemas /usr/share/glib-2.0/schemas*

**Comment by somas95** [comment]
Hi! Could you post here the console output? I can't reproduce the issue. Maybe we are trying to display a non-existing document? I would think that there is an issue with portals, but you tried a non-flatpak version too

**Comment by tonhou** [comment]
This is all I get when starting from terminal:

flatpak run de.wolfvollprecht.UberWriter

(uberwriter:3): dbind-WARNING **: 17:09:02.089: AT-SPI: Error retrieving
accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown:
org.freedesktop.DBus.Error.ServiceUnknown
WARNING:uberwriter_lib.gtkspellcheck.spellcheck: __init__() 'no installed
dictionary for language "en_AG" and english, fallback to first language
inlanguage list ("en_AU")'

No further output when I open a file.

NB. This is from a further (Debian) install and flatpak - but on the same
laptop detailed as follows:

$ inxi -Fxzd
System:
  Host: hplaptop Kernel: 4.9.0-9-amd64 x86_64 bits: 64 compiler: gcc
  v: 6.3.0 Desktop: Cinnamon 4.0.10 Distro: LMDE 3 Cindy
  base: Debian 9.3 stretch
Machine:
  Type: Laptop System: Hewlett-Packard product: HP EliteBook 8560p
  v: A0001C02 serial: <filter>
  Mobo: Hewlett-Packard model: 1618 v: KBC Version 97.4D serial: <filter>
  BIOS: Hewlett-Packard v: 68SCF Ver. F.42 date: 07/15/2013
Battery:
  ID-1: BAT0 charge: 48.1 Wh condition: 49.5/49.5 Wh (100%)
  model: Hewlett-Packard Primary status: Unknown
CPU:
  Topology: Dual Core model: Intel Core i5-2540M bits: 64 type: MT MCP
  arch: Sandy Bridge rev: 7 L2 cache: 3072 KiB
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20752
  Speed: 916 MHz min/max: 800/3300 MHz Core speeds (MHz): 1: 916 2: 893
  3: 938 4: 970
Graphics:
  Device-1: AMD Seymour [Radeon HD 6400M/7400M Series]
  vendor: Hewlett-Packard driver: radeon v: kernel bus ID: 01:00.0
  Display: x11 server: X.Org 1.19.2 driver: ati,radeon
  unloaded: fbdev,modesetting,vesa resolution: 1600x900~60Hz
  OpenGL:
  renderer: Gallium 0.4 on AMD CAICOS (DRM 2.49.0 / 4.9.0-9-amd64 LLVM
3.9.1)
  v: 3.3 Mesa 13.0.6 direct render: Yes
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio
  vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 00:1b.0
  Sound Server: ALSA v: k4.9.0-9-amd64
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Hewlett-Packard
  driver: e1000e v: 3.2.6-k port: 5020 bus ID: 00:19.0
  IF: enp0s25 state: down mac: <filter>
  Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi
  v: kernel port: 4000 bus ID: 25:00.0
  IF: wlo1 state: up mac: <filter>
Drives:
  Local Storage: total: 465.76 GiB used: 194.15 GiB (41.7%)
  ID-1: /dev/sda vendor: Western Digital model: WD5000LPVX-00V0TT0
  size: 465.76 GiB
  Optical-1: /dev/sr0 vendor: hp model: CDDVDW TS-L633J rev: HH00
  dev-links: cdrom,cdrw,dvd,dvdrw
  Features: speed: 24 multisession: yes audio: yes dvd: yes
  rw: cd-r,cd-rw,dvd-r,dvd-ram state: running
Partition:
  ID-1: / size: 248.91 GiB used: 64.33 GiB (25.8%) fs: ext4 dev: /dev/sda6
  ID-2: swap-1 size: 1.59 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda5
Sensors:
  System Temperatures: cpu: 52.0 C mobo: 52.0 C gpu: radeon temp: 54 C
  Fan Speeds (RPM): N/A
Info:
  Processes: 228 Uptime: 2h 55m Memory: 7.75 GiB used: 1.70 GiB (22.0%)
  Init: systemd runlevel: 5 Compilers: gcc: 6.3.0 Shell: bash v: 4.4.12
  inxi: 3.0.32

**Comment by somas95** [comment]
I fired a new Debian 9 VM, installed plasma, installed uberwriter from flathub... and I can't reproduce your issue
I don't know how to approach this
Installing at-spi2-core should solve the warning, but I don't think that's the problem
Maybe uninstall both uberwriter _and_ the latex plugin and install them again?
Also, I don't think I correctly understood the issue. It happens when opening from the recents menu? When you do that, the titlebar changes to reflect the "opened" file?

**Comment by tonhou** [comment]
*ALL* opened documents are blank (as heading and original post described) -
with the one exception that the "Markdown Tutorial" document loads and can
be viewed correctly (as detailed in original). The title bar shows the name
of the document.
I have done a clean install of Mageia 7 and a new Flatpak install of
Uberwriter and TexLive. The behaviour is still the same.
I can only assume that there is an incompatibility with this hardware.
I used older Uberwriter for a couple of years without issue on this
hardware.

**Comment by somas95** [comment]
What happens if you try to open a file that you know that it exists from the console?
`flatpak run de.wolfvollprecht.UberWriter /home/user/existing_file.md`

I just realized: if you try to open a non-existing file, uberwriter will "open" a blank one with the title of the file you tried to open. So, maybe we're trying to open files wrongly (non read permissions, wrong parsing of the file URI...)

I don't think it's a hardware issue, we have multiple layers of abstraction. But definitively seems a "only happens to one or two persons" bug. 

Let's see if we can spot the issue. In the meantime I'll add warnings for those kind of file access errors to the next version

**Comment by tonhou** [comment]
OK, some progress.
I think you are on to it concerning some permissions issue etc.
My files are in a sync folder which uploads to Google Drive
If I shift files to my home directory they open and display - or in fact
any other folder I think.

Thanks for your patience and direction with this.
Is there a work around do you think for this situation?
Oddly other markdown editors don't seem bothered by this.

**Comment by somas95** [comment]
Can I ask how are you syncing with Google Drive? I know gnome has native integration, but I don't use plasma since 2014. I installed Debian with KDE on a virtual machine to test this, maybe I might find a workaround
I handle "file://" URIs, with a little luck handling "kio://" ones it's as easy (or maybe it's a nightmare)
________________________________

**Comment by tonhou** [comment]
I use "Insync"  https://www.insynchq.com/
The permissions thing may also have been complicated by my copying the
directory from one partition to another.
I have been looking at kio-gdrive, but have not adopted it as it seems a
little erratic, and find it difficult to access files at all.

**Comment by tonhou** [comment]
Further discovery.
The folder I had documents in was "Documents 2018+"
It seems that "+" is not generally accepted as part of a folder name.
Removing that allows Uberwriter to display documents without issue.

So .... it would appear that that is the issue!

**Comment by somas95** [comment]
Great! Sounds *a lot* like I'm not escaping properly the path somewhere. I'll look after this this afternoon
Thanks for the patience!
________________________________

**Comment by somas95** [comment]
I spotted the faulty code. It'll be fixed in the next release, in the meantime you can use the non-flatpak version. I'll attach here the git tag of the project where this is fixed, and everything stable. Expect it the next days, and the official release in a mont or two (if we weren't redoing even the buildsystem I would push this to the beta channel on flathub)
